// 
// Decompiled by Procyon v0.5.36
// 

package dev.nuker.pyro.deobfuscated.main;

import dev.nuker.pyro.deobfuscated.gui.hud.items.SelectorMenuComponent;
import dev.nuker.pyro.deobfuscated.gui.hud.items.ArrayListComponent;
import dev.nuker.pyro.deobfuscated.module.combat.Offhand;
import dev.nuker.pyro.deobfuscated.module.render.ItemPhysics;
import dev.nuker.pyro.deobfuscated.module.render.NoRender;
import dev.nuker.pyro.deobfuscated.module.misc.ImgurUploader;
import dev.nuker.pyro.deobfuscated.module.world.NoGlitchBlocks;
import dev.nuker.pyro.deobfuscated.module.movement.Blink;
import dev.nuker.pyro.deobfuscated.module.movement.BoatFly;
import dev.nuker.pyro.deobfuscated.module.movement.ElytraFly;
import dev.nuker.pyro.deobfuscated.module.exploit.Reach;
import dev.nuker.pyro.deobfuscated.module.movement.NoRotate;
import dev.nuker.pyro.deobfuscated.module.exploit.PacketFly;
import dev.nuker.pyro.deobfuscated.module.render.ViewClip;
import dev.nuker.pyro.deobfuscated.module.combat.Criticals;
import dev.nuker.pyro.deobfuscated.module.ui.Hud;
import dev.nuker.pyro.deobfuscated.module.world.StashLogger;
import dev.nuker.pyro.deobfuscated.module.movement.NoSlow;
import dev.nuker.pyro.deobfuscated.module.exploit.LiquidInteract;
import dev.nuker.pyro.deobfuscated.module.misc.Friends;
import dev.nuker.pyro.deobfuscated.module.ui.ReliantChat;
import dev.nuker.pyro.deobfuscated.module.misc.StopWatch;
import dev.nuker.pyro.deobfuscated.module.exploit.PacketCanceller;
import dev.nuker.pyro.deobfuscated.module.ui.Colors;
import dev.nuker.pyro.deobfuscated.module.movement.HoleFinder;
import dev.nuker.pyro.deobfuscated.module.ui.ClickGui;
import dev.nuker.pyro.deobfuscated.module.misc.ChestStealer;
import dev.nuker.pyro.deobfuscated.module.exploit.EntityDesync;
import dev.nuker.pyro.deobfuscated.module.world.AutoTunnel;
import dev.nuker.pyro.deobfuscated.module.bot.DupeBot;
import dev.nuker.pyro.deobfuscated.module.misc.AutoReconnect;
import dev.nuker.pyro.deobfuscated.module.misc.DiscordRPC;
import dev.nuker.pyro.deobfuscated.module.render.Freecam;
import dev.nuker.pyro.deobfuscated.module.movement.Flight;
import dev.nuker.pyro.deobfuscated.module.world.TimerModule;
import dev.nuker.pyro.deobfuscated.module.combat.HoleFiller;
import dev.nuker.pyro.deobfuscated.module.misc.AutoMendArmor;
import dev.nuker.pyro.deobfuscated.module.combat.AutoCity;
import dev.nuker.pyro.deobfuscated.module.ui.Keybinds;
import dev.nuker.pyro.deobfuscated.module.combat.SelfTrap;
import dev.nuker.pyro.deobfuscated.module.combat.AutoTrapFeet;
import dev.nuker.pyro.deobfuscated.module.combat.AutoTrap;
import dev.nuker.pyro.deobfuscated.module.movement.Speed;
import dev.nuker.pyro.deobfuscated.module.combat.Surround;
import dev.nuker.pyro.deobfuscated.module.combat.AutoCrystal;
import dev.nuker.pyro.deobfuscated.module.combat.Aura;
import dev.nuker.pyro.deobfuscated.module.combat.AutoTotem;
import dev.nuker.pyro.deobfuscated.module.movement.AutoWalk;
import dev.nuker.pyro.deobfuscated.module.misc.ChorusFruitBypass;
import dev.nuker.pyro.deobfuscated.module.misc.ChatModifications;
import dev.nuker.pyro.deobfuscated.module.render.StorageESP;
import dev.nuker.pyro.deobfuscated.module.render.EntityESP;
import dev.nuker.pyro.deobfuscated.module.render.Wallhack;
import dev.nuker.pyro.deobfuscated.module.world.StashFinder;
import dev.nuker.pyro.deobfuscated.module.combat.AutoArmor;
import dev.nuker.pyro.deobfuscated.module.misc.Annoy;
import dev.nuker.pyro.deobfuscated.module.misc.AntiAFK;

public class PyroStatic
{
    public static AntiAFK ANTIAFK;
    public static Annoy ANNOY;
    public static AutoArmor AUTOARMOR;
    public static StashFinder STASHFINDER;
    public static Wallhack WALLHACK;
    public static EntityESP ENTITYESP;
    public static StorageESP STORAGEESP;
    public static ChatModifications CHATMODIFICATIONS;
    public static ChorusFruitBypass CHORUSFRUITBYPASS;
    public static AutoWalk AUTOWALK;
    public static AutoTotem AUTOTOTEM;
    public static Aura AURA;
    public static AutoCrystal AUTOCRYSTAL;
    public static Surround SURROUND;
    public static Speed SPEED;
    public static AutoTrap AUTOTRAP;
    public static AutoTrapFeet AUTOTRAPFEET;
    public static SelfTrap SELFTRAP;
    public static Keybinds KEYBINDS;
    public static AutoCity AUTOCITY;
    public static AutoMendArmor AUTOMEND;
    public static HoleFiller HOLEFILLER;
    public static TimerModule TIMER;
    public static Flight FLIGHT;
    public static Freecam FREECAM;
    public static DiscordRPC DISCORDRPC;
    public static AutoReconnect AUTORECONNECT;
    public static DupeBot DUPEBOT;
    public static AutoTunnel AUTOTUNNEL;
    public static EntityDesync ENTITYDESYNC;
    public static ChestStealer CHESTSTEALER;
    public static ClickGui CLICKGUI;
    public static HoleFinder HOLEFINDER;
    public static Colors COLORS;
    public static PacketCanceller PACKETCANCELLER;
    public static StopWatch STOPWATCH;
    public static ReliantChat RELIANTCHAT;
    public static Friends FRIENDS;
    public static LiquidInteract LIQUIDINTERACT;
    public static NoSlow NOSLOW;
    public static StashLogger STASHLOGGER;
    public static Hud HUD;
    public static Criticals CRITICALS;
    public static ViewClip VIEWCLIP;
    public static PacketFly PACKETFLY;
    public static NoRotate NOROTATE;
    public static Reach REACH;
    public static ElytraFly ELYTRAFLY;
    public static BoatFly BOATFLY;
    public static Blink BLINK;
    public static NoGlitchBlocks NOGLITCHBLOCKS;
    public static ImgurUploader IMGURUPLOADER;
    public static NoRender NORENDER;
    public static ItemPhysics ITEMPHYSICS;
    public static Offhand OFFHAND;
    public static ArrayListComponent ARRAYLIST;
    public static SelectorMenuComponent SELECTORMENU;
}
